# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "adrian-lab-kso-q3-terraform-state"
    dynamodb_table = "adrian-terraform-state-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-2"
  }
}
